# Bindings for wavemeter dll
# Original: Daqing Wang, 2019.07
# Modifications by Jonas Keller, 2020.05

from typing import Any, List
from ctypes import (
    CDLL,
    cdll,
    c_bool,
    c_short,
    c_char,
    c_long,
    c_double,
    c_ushort,
    c_ulong,
    c_void_p,
    POINTER,
    CFUNCTYPE,
)

c_word = c_ushort
c_dword = c_ulong


def null_function():
    pass


def bind(lib: CDLL, func: str,
         argtypes: List[Any] = None, restype: Any = None) -> CFUNCTYPE:
    _func = getattr(lib, func, null_function)
    _func.argtypes = argtypes
    _func.restype = restype

    return _func


class HFDLL:
    def __init__(self):
        # load dll
        try:
            self.lib = cdll.LoadLibrary("wlmData.dll")
        except FileNotFoundError:
            raise Exception("\"wlmData.dll\" not found. Is the wavemeter software installed correctly?")

        # binds
        self.Instantiate = bind(self.lib, "Instantiate", [c_long, c_long, POINTER(c_long), c_long], c_long)
        self.ControlWLM = bind(self.lib, "ControlWLM", [c_long, POINTER(c_char), c_long], c_long)
        self.Operation = bind(self.lib, "Operation", [c_short], c_long)

        self.GetWavelengthNum = bind(self.lib, "GetWavelengthNum", [c_long, c_double], c_double)
        self.GetFrequencyNum = bind(self.lib, "GetFrequencyNum", [c_long, c_double], c_double)

        self.GetExposureModeNum = bind(self.lib, "GetExposureModeNum", [c_long, c_bool], c_bool)
        self.SetExposureModeNum = bind(self.lib, "SetExposureModeNum", [c_long, c_bool], c_long)

        self.GetExposureNum = bind(self.lib, "GetExposureNum", [c_long, c_long, c_long], c_long)
        self.SetExposureNum = bind(self.lib, "SetExposureNum", [c_long, c_long, c_long], c_long)

        self.GetSwitcherMode = bind(self.lib, "GetSwitcherMode", [c_long], c_bool)
        self.SetSwitcherMode = bind(self.lib, "SetSwitcherMode", [c_long], c_long)

        self.Calibration = bind(self.lib, "Calibration", [c_long, c_long, c_double, c_long], c_long)

        self.SetPattern = bind(self.lib, "SetPattern", [c_long, c_long], c_long)
        self.GetPatternItemCount = bind(self.lib, "GetPatternItemCount", [c_long], c_long)
        self.GetPatternItemSize = bind(self.lib, "GetPatternItemSize", [c_long], c_long)
        self.GetPatternNum = bind(self.lib, "GetPatternNum", [c_long, c_long], c_long)
        self.GetPatternDataNum = bind(self.lib, "GetPatternDataNum", [c_long, c_long, c_void_p], c_long)

        # constants from wlmData.h
        # return values for set functions
        self.ResErr = {0: "ResERR_NoErr",
                       -1: "ResERR_WlmMissing",
                       -2: "ResERR_CouldNotSet",
                       -3: "ResERR_ParmOutOfRange",
                       -4: "ResERR_WlmOutOfResources",
                       -5: "ResERR_WlmInternalError",
                       -6: "ResERR_NotAvailable",
                       -7: "ResERR_WlmBusy",
                       -8: "ResERR_NotInMeasurementMode",
                       -9: "ResERR_OnlyInMeasurementMode",
                       -10: "ResERR_ChannelNotAvailable",
                       -11: "ResERR_ChannelTemporarilyNotAvailable",
                       -12: "ResERR_CalOptionNotAvailable",
                       -13: "ResERR_CalWavelengthOutOfRange",
                       -14: "ResERR_BadCalibrationSignal",
                       -15: "ResERR_UnitNotAvailable",
                       -16: "ResERR_FileNotFound",
                       -17: "ResERR_FileCreation",
                       -18: "ResERR_TriggerPending",
                       -19: "ResERR_TriggerWaiting",
                       -20: "ResERR_NoLegitimation",
                       -21: "ResERR_NoTCPLegitimation",
                       -22: "ResERR_NotInPulseMode",
                       -23: "ResERR_OnlyInPulseMode",
                       -24: "ResERR_NotInSwitchMode",
                       -25: "ResERR_OnlyInSwitchMode",
                       -26: "ResERR_TCPErr"}

        # return values for get functions
        self.Err = {0: "ErrNoValue",
                    -1: "ErrNoSignal",
                    -2: "ErrBadSignal",
                    -3: "ErrLowSignal",
                    -4: "ErrBigSignal",
                    -5: "ErrWlmMissing",
                    -6: "ErrNotAvailable",
                    -7: "InfNothingChanged",
                    -8: "ErrNoPulse",
                    -10: "ErrChannelNotAvailable",
                    -13: "ErrDiv0",
                    -14: "ErrOutOfRange",
                    -15: "ErrUnitNotAvailable",
                    -26: "ErrTCPErr",
                    -26: "ErrMaxErr",
                    -1000: "ErrTemperature",
                    -1000: "ErrTempNotMeasured",
                    -1006: "ErrTempNotAvailable",
                    -1005: "ErrTempWlmMissing",
                    -1000000000: "ErrDistance",
                    -1000000006: "ErrDistanceNotAvailable",
                    -1000000005: "ErrDistanceWlmMissing"}

        self.const = {"cInstCheckForWLM": -1,
                      "cInstResetCalc": 0,
                      "cInstReturnMode": 0,
                      "cInstNotification": 1,
                      "cInstCopyPattern": 2,
                      "cInstCopyAnalysis": 2,
                      "cInstControlWLM": 3,
                      "cInstControlDelay": 4,
                      "cInstControlPriority": 5,
                      "cNotifyInstallCallback": 0,
                      "cNotifyRemoveCallback": 1,
                      "cNotifyInstallWaitEvent": 2,
                      "cNotifyRemoveWaitEvent": 3,
                      "cNotifyInstallCallbackEx": 4,
                      "cNotifyInstallWaitEventEx": 5,
                      "cmiResultMode": 1,
                      "cmiRange": 2,
                      "cmiPulse": 3,
                      "cmiPulseMode": 3,
                      "cmiWideLine": 4,
                      "cmiWideMode": 4,
                      "cmiFast": 5,
                      "cmiFastMode": 5,
                      "cmiExposureMode": 6,
                      "cmiExposureValue1": 7,
                      "cmiExposureValue2": 8,
                      "cmiDelay": 9,
                      "cmiShift": 10,
                      "cmiShift2": 11,
                      "cmiReduce": 12,
                      "cmiReduced": 12,
                      "cmiScale": 13,
                      "cmiTemperature": 14,
                      "cmiLink": 15,
                      "cmiOperation": 16,
                      "cmiDisplayMode": 17,
                      "cmiPattern1a": 18,
                      "cmiPattern1b": 19,
                      "cmiPattern2a": 20,
                      "cmiPattern2b": 21,
                      "cmiMin1": 22,
                      "cmiMax1": 23,
                      "cmiMin2": 24,
                      "cmiMax2": 25,
                      "cmiNowTick": 26,
                      "cmiCallback": 27,
                      "cmiFrequency1": 28,
                      "cmiFrequency2": 29,
                      "cmiDLLDetach": 30,
                      "cmiVersion": 31,
                      "cmiAnalysisMode": 32,
                      "cmiDeviationMode": 33,
                      "cmiDeviationReference": 34,
                      "cmiDeviationSensitivity": 35,
                      "cmiAppearance": 36,
                      "cmiAutoCalMode": 37,
                      "cmiWavelength1": 42,
                      "cmiWavelength2": 43,
                      "cmiLinewidth": 44,
                      "cmiLinewidthMode": 45,
                      "cmiLinkDlg": 56,
                      "cmiAnalysis": 57,
                      "cmiAnalogIn": 66,
                      "cmiAnalogOut": 67,
                      "cmiDistance": 69,
                      "cmiWavelength3": 90,
                      "cmiWavelength4": 91,
                      "cmiWavelength5": 92,
                      "cmiWavelength6": 93,
                      "cmiWavelength7": 94,
                      "cmiWavelength8": 95,
                      "cmiVersion0": 31,
                      "cmiVersion1": 96,
                      "cmiPulseDelay": 99,
                      "cmiDLLAttach": 121,
                      "cmiSwitcherSignal": 123,
                      "cmiSwitcherMode": 124,
                      "cmiExposureValue11": 7,
                      "cmiExposureValue12": 125,
                      "cmiExposureValue13": 126,
                      "cmiExposureValue14": 127,
                      "cmiExposureValue15": 128,
                      "cmiExposureValue16": 129,
                      "cmiExposureValue17": 130,
                      "cmiExposureValue18": 131,
                      "cmiExposureValue21": 8,
                      "cmiExposureValue22": 132,
                      "cmiExposureValue23": 133,
                      "cmiExposureValue24": 134,
                      "cmiExposureValue25": 135,
                      "cmiExposureValue26": 136,
                      "cmiExposureValue27": 137,
                      "cmiExposureValue28": 138,
                      "cmiPatternAverage": 139,
                      "cmiPatternAvg1": 140,
                      "cmiPatternAvg2": 141,
                      "cmiAnalogOut1": 67,
                      "cmiAnalogOut2": 142,
                      "cmiMin11": 22,
                      "cmiMin12": 146,
                      "cmiMin13": 147,
                      "cmiMin14": 148,
                      "cmiMin15": 149,
                      "cmiMin16": 150,
                      "cmiMin17": 151,
                      "cmiMin18": 152,
                      "cmiMin21": 24,
                      "cmiMin22": 153,
                      "cmiMin23": 154,
                      "cmiMin24": 155,
                      "cmiMin25": 156,
                      "cmiMin26": 157,
                      "cmiMin27": 158,
                      "cmiMin28": 159,
                      "cmiMax11": 23,
                      "cmiMax12": 160,
                      "cmiMax13": 161,
                      "cmiMax14": 162,
                      "cmiMax15": 163,
                      "cmiMax16": 164,
                      "cmiMax17": 165,
                      "cmiMax18": 166,
                      "cmiMax21": 25,
                      "cmiMax22": 167,
                      "cmiMax23": 168,
                      "cmiMax24": 169,
                      "cmiMax25": 170,
                      "cmiMax26": 171,
                      "cmiMax27": 172,
                      "cmiMax28": 173,
                      "cmiAvg11": 140,
                      "cmiAvg12": 174,
                      "cmiAvg13": 175,
                      "cmiAvg14": 176,
                      "cmiAvg15": 177,
                      "cmiAvg16": 178,
                      "cmiAvg17": 179,
                      "cmiAvg18": 180,
                      "cmiAvg21": 141,
                      "cmiAvg22": 181,
                      "cmiAvg23": 182,
                      "cmiAvg24": 183,
                      "cmiAvg25": 184,
                      "cmiAvg26": 185,
                      "cmiAvg27": 186,
                      "cmiAvg28": 187,
                      "cmiPatternAnalysisWritten": 202,
                      "cmiSwitcherChannel": 203,
                      "cmiStartCalibration": 235,
                      "cmiEndCalibration": 236,
                      "cmiAnalogOut3": 237,
                      "cmiAnalogOut4": 238,
                      "cmiAnalogOut5": 239,
                      "cmiAnalogOut6": 240,
                      "cmiAnalogOut7": 241,
                      "cmiAnalogOut8": 242,
                      "cmiIntensity": 251,
                      "cmiPower": 267,
                      "cmiActiveChannel": 300,
                      "cmiPIDCourse": 1030,
                      "cmiPIDUseTa": 1031,
                      "cmiPIDUseT": 1031,
                      "cmiPID_T": 1033,
                      "cmiPID_P": 1034,
                      "cmiPID_I": 1035,
                      "cmiPID_D": 1036,
                      "cmiDeviationSensitivityDim": 1040,
                      "cmiDeviationSensitivityFactor": 1037,
                      "cmiDeviationPolarity": 1038,
                      "cmiDeviationSensitivityEx": 1039,
                      "cmiDeviationUnit": 1041,
                      "cmiDeviationBoundsMin": 1042,
                      "cmiDeviationBoundsMax": 1043,
                      "cmiDeviationRefMid": 1044,
                      "cmiDeviationRefAt": 1045,
                      "cmiPIDConstdt": 1059,
                      "cmiPID_dt": 1060,
                      "cmiPID_AutoClearHistory": 1061,
                      "cmiDeviationChannel": 1063,
                      "cmiPID_ClearHistoryOnRangeExceed": 1069,
                      "cmiAutoCalPeriod": 1120,
                      "cmiAutoCalUnit": 1121,
                      "cmiAutoCalChannel": 1122,
                      "cmiServerInitialized": 1124,
                      "cmiWavelength9": 1130,
                      "cmiExposureValue19": 1155,
                      "cmiExposureValue29": 1180,
                      "cmiMin19": 1205,
                      "cmiMin29": 1230,
                      "cmiMax19": 1255,
                      "cmiMax29": 1280,
                      "cmiAvg19": 1305,
                      "cmiAvg29": 1330,
                      "cmiWavelength10": 1355,
                      "cmiWavelength11": 1356,
                      "cmiWavelength12": 1357,
                      "cmiWavelength13": 1358,
                      "cmiWavelength14": 1359,
                      "cmiWavelength15": 1360,
                      "cmiWavelength16": 1361,
                      "cmiWavelength17": 1362,
                      "cmiExternalInput": 1400,
                      "cmiPressure": 1465,
                      "cmiBackground": 1475,
                      "cmiDistanceMode": 1476,
                      "cmiInterval": 1477,
                      "cmiIntervalMode": 1478,
                      "cmiCalibrationEffect": 1480,
                      "cmiLinewidth1": 44,
                      "cmiLinewidth2": 1481,
                      "cmiLinewidth3": 1482,
                      "cmiLinewidth4": 1483,
                      "cmiLinewidth5": 1484,
                      "cmiLinewidth6": 1485,
                      "cmiLinewidth7": 1486,
                      "cmiLinewidth8": 1487,
                      "cmiLinewidth9": 1488,
                      "cmiLinewidth10": 1489,
                      "cmiLinewidth11": 1490,
                      "cmiLinewidth12": 1491,
                      "cmiLinewidth13": 1492,
                      "cmiLinewidth14": 1493,
                      "cmiLinewidth15": 1494,
                      "cmiLinewidth16": 1495,
                      "cmiLinewidth17": 1496,
                      "cmiTriggerState": 1497,
                      "cmiDeviceAttach": 1501,
                      "cmiDeviceDetach": 1502,
                      "cmiTimePerMeasurement": 1514,
                      "cmiAutoExpoMin": 1517,
                      "cmiAutoExpoMax": 1518,
                      "cmiAutoExpoStepUp": 1519,
                      "cmiAutoExpoStepDown": 1520,
                      "cmiAutoExpoAtSaturation": 1521,
                      "cmiAutoExpoAtLowSignal": 1522,
                      "cmiAutoExpoFeedback": 1523,
                      "cmiAveragingCount": 1524,
                      "cmiAveragingMode": 1525,
                      "cmiAveragingType": 1526,
                      "cmiAirMode": 1532,
                      "cmiAirTemperature": 1534,
                      "cmiAirPressure": 1535,
                      "cmiAirHumidity": 1536,
                      "cesCalculateLive": 4501,
                      "cCtrlWLMShow": 1,
                      "cCtrlWLMHide": 2,
                      "cCtrlWLMExit": 3,
                      "cCtrlWLMStore": 4,
                      "cCtrlWLMCompare": 5,
                      "cCtrlWLMWait": 0x0010,
                      "cCtrlWLMStartSilent": 0x0020,
                      "cCtrlWLMSilent": 0x0040,
                      "cCtrlWLMStartDelay": 0x0080,
                      "cStop": 0,
                      "cAdjustment": 1,
                      "cMeasurement": 2,
                      "cCtrlStopAll": 0,
                      "cCtrlStartAdjustment": 1,
                      "cCtrlStartMeasurement": 2,
                      "cCtrlStartRecord": 0x0004,
                      "cCtrlStartReplay": 0x0008,
                      "cCtrlStoreArray": 0x0010,
                      "cCtrlLoadArray": 0x0020,
                      "cCtrlDontOverwrite": 0x0000,
                      "cCtrlOverwrite": 0x1000,
                      "cCtrlFileGiven": 0x0000,
                      "cCtrlFileDialog": 0x2000,
                      "cCtrlFileBinary": 0x0000,
                      "cCtrlFileASCII": 0x4000,
                      "cCtrlMeasDelayRemove": 0,
                      "cCtrlMeasDelayGenerally": 1,
                      "cCtrlMeasDelayOnce": 2,
                      "cCtrlMeasDelayDenyUntil": 3,
                      "cCtrlMeasDelayIdleOnce": 4,
                      "cCtrlMeasDelayIdleEach": 5,
                      "cCtrlMeasDelayDefault": 6,
                      "cCtrlMeasurementContinue": 0,
                      "cCtrlMeasurementInterrupt": 1,
                      "cCtrlMeasurementTriggerPoll": 2,
                      "cCtrlMeasurementTriggerSuccess": 3,
                      "cCtrlMeasurementEx": 0x0100,
                      "cExpoMin": 0,
                      "cExpoMax": 1,
                      "cExpo2Min": 2,
                      "cExpo2Max": 3,
                      "cMin1": 0,
                      "cMin2": 1,
                      "cMax1": 2,
                      "cMax2": 3,
                      "cAvg1": 4,
                      "cAvg2": 5,
                      "cRange_250_410": 4,
                      "cRange_250_425": 0,
                      "cRange_300_410": 3,
                      "cRange_350_500": 5,
                      "cRange_400_725": 1,
                      "cRange_700_1100": 2,
                      "cRange_800_1300": 6,
                      "cRange_900_1500": 6,
                      "cRange_1100_1700": 7,
                      "cRange_1100_1800": 7,
                      "cRangeModelOld": 65535,
                      "cRangeModelByOrder": 65534,
                      "cRangeModelByWavelength": 65533,
                      "cReturnWavelengthVac": 0,
                      "cReturnWavelengthAir": 1,
                      "cReturnFrequency": 2,
                      "cReturnWavenumber": 3,
                      "cReturnPhotonEnergy": 4,
                      "cPower_muW": 0,
                      "cPower_dBm": 1,
                      "cHeNe633": 0,
                      "cHeNe1152": 0,
                      "cNeL": 1,
                      "cOther": 2,
                      "cFreeHeNe": 3,
                      "cSLR1530": 5,
                      "cACOnceOnStart": 0,
                      "cACMeasurements": 1,
                      "cACDays": 2,
                      "cACHours": 3,
                      "cACMinutes": 4,
                      "cGetSync": 1,
                      "cSetSync": 2,
                      "cPatternDisable": 0,
                      "cPatternEnable": 1,
                      "cAnalysisDisable": 0,
                      "cAnalysisEnable": 1,
                      "cSignal1Interferometers": 0,
                      "cSignal1WideInterferometer": 1,
                      "cSignal1Grating": 1,
                      "cSignal2Interferometers": 2,
                      "cSignal2WideInterferometer": 3,
                      "cSignalAnalysis": 4,
                      "cSignalAnalysisX": 4,
                      "cSignalAnalysisY": 5,
                      "cJustStepDown": 0,
                      "cRestartAtMinimum": 1,
                      "cJustStepUp": 0,
                      "cDriveToLevel": 1,
                      "cConsiderFeedback": 1,
                      "cDontConsiderFeedback": 0,
                      "cAvrgFloating": 1,
                      "cAvrgSucceeding": 2,
                      "cAvrgSimple": 0,
                      "cAvrgPattern": 1}
